### ISSUE TITLE
food: dumpster dive

### ISSUE THREAD

**Issue by guaka** [squatconf/manifest#1]
http://trashwiki.org/en/Paris is a start

**Comment by gorhgorh** [comment]
yep, still loads of people actually need it to survive and providing food for a conference does not fit. 
on top of that, most of the shops now put bleach on it to avoid problems if someone's gets ill from consumption :(

**Comment by elf-pavlik** [comment]
@gorhgorh do you know people from http://discosoupe.org/ ?

**Comment by gorhgorh** [comment]
not personally but i knew about the initiative and may know ppl that does, and yes we should definitly make a "disco soupe" :)
